<?xml version="1.0" encoding="utf-8"?>
<Database Name="CMS" Class="ACLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CMS.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.resources" Member="resources">
    <Type Name="resource">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="controller" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="action" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="resource_role_resource" Member="role_resources" OtherKey="resourcesid" Type="role_resource" />
    </Type>
  </Table>
  <Table Name="dbo.roles_resources" Member="role_resources">
    <Type Name="role_resource">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="resourcesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="rolesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="resource_role_resource" Member="resource" ThisKey="resourcesid" Type="resource" IsForeignKey="true" />
      <Association Name="role_role_resource" Member="role" ThisKey="rolesid" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.roles" Member="roles">
    <Type Name="role">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="parentid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="role_role_resource" Member="role_resources" OtherKey="rolesid" Type="role_resource" />
      <Association Name="role_role" Member="roles" OtherKey="parentid" Type="role" />
      <Association Name="role_role" Member="role1" ThisKey="parentid" Type="role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>