#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="CMS")]
	public partial class ArticleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttag(tag instance);
    partial void Updatetag(tag instance);
    partial void Deletetag(tag instance);
    partial void Inserttags_article(tags_article instance);
    partial void Updatetags_article(tags_article instance);
    partial void Deletetags_article(tags_article instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertauthor(author instance);
    partial void Updateauthor(author instance);
    partial void Deleteauthor(author instance);
    partial void Insertarticle(article instance);
    partial void Updatearticle(article instance);
    partial void Deletearticle(article instance);
    partial void Insertarticles_author(articles_author instance);
    partial void Updatearticles_author(articles_author instance);
    partial void Deletearticles_author(articles_author instance);
    partial void Insertarticles_category(articles_category instance);
    partial void Updatearticles_category(articles_category instance);
    partial void Deletearticles_category(articles_category instance);
    partial void Insertcomment(comment instance);
    partial void Updatecomment(comment instance);
    partial void Deletecomment(comment instance);
    #endregion
		
		public ArticleDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CMSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArticleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArticleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tag> tags
		{
			get
			{
				return this.GetTable<tag>();
			}
		}
		
		public System.Data.Linq.Table<tags_article> tags_articles
		{
			get
			{
				return this.GetTable<tags_article>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<author> authors
		{
			get
			{
				return this.GetTable<author>();
			}
		}
		
		public System.Data.Linq.Table<article> articles
		{
			get
			{
				return this.GetTable<article>();
			}
		}
		
		public System.Data.Linq.Table<articles_author> articles_authors
		{
			get
			{
				return this.GetTable<articles_author>();
			}
		}
		
		public System.Data.Linq.Table<articles_category> articles_categories
		{
			get
			{
				return this.GetTable<articles_category>();
			}
		}
		
		public System.Data.Linq.Table<comment> comments
		{
			get
			{
				return this.GetTable<comment>();
			}
		}
	}
	
	[Table(Name="dbo.tags")]
	public partial class tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private System.DateTime _date;
		
		private EntitySet<tags_article> _tags_articles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public tag()
		{
			this._tags_articles = new EntitySet<tags_article>(new Action<tags_article>(this.attach_tags_articles), new Action<tags_article>(this.detach_tags_articles));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Association(Name="tag_tags_article", Storage="_tags_articles", OtherKey="tagsid")]
		public EntitySet<tags_article> tags_articles
		{
			get
			{
				return this._tags_articles;
			}
			set
			{
				this._tags_articles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tags_articles(tags_article entity)
		{
			this.SendPropertyChanging();
			entity.tag = this;
		}
		
		private void detach_tags_articles(tags_article entity)
		{
			this.SendPropertyChanging();
			entity.tag = null;
		}
	}
	
	[Table(Name="dbo.tags_articles")]
	public partial class tags_article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _tagsid;
		
		private long _articlesid;
		
		private EntityRef<tag> _tag;
		
		private EntityRef<article> _article;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OntagsidChanging(long value);
    partial void OntagsidChanged();
    partial void OnarticlesidChanging(long value);
    partial void OnarticlesidChanged();
    #endregion
		
		public tags_article()
		{
			this._tag = default(EntityRef<tag>);
			this._article = default(EntityRef<article>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_tagsid", DbType="BigInt NOT NULL")]
		public long tagsid
		{
			get
			{
				return this._tagsid;
			}
			set
			{
				if ((this._tagsid != value))
				{
					if (this._tag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntagsidChanging(value);
					this.SendPropertyChanging();
					this._tagsid = value;
					this.SendPropertyChanged("tagsid");
					this.OntagsidChanged();
				}
			}
		}
		
		[Column(Storage="_articlesid", DbType="BigInt NOT NULL")]
		public long articlesid
		{
			get
			{
				return this._articlesid;
			}
			set
			{
				if ((this._articlesid != value))
				{
					if (this._article.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnarticlesidChanging(value);
					this.SendPropertyChanging();
					this._articlesid = value;
					this.SendPropertyChanged("articlesid");
					this.OnarticlesidChanged();
				}
			}
		}
		
		[Association(Name="tag_tags_article", Storage="_tag", ThisKey="tagsid", IsForeignKey=true)]
		public tag tag
		{
			get
			{
				return this._tag.Entity;
			}
			set
			{
				tag previousValue = this._tag.Entity;
				if (((previousValue != value) 
							|| (this._tag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tag.Entity = null;
						previousValue.tags_articles.Remove(this);
					}
					this._tag.Entity = value;
					if ((value != null))
					{
						value.tags_articles.Add(this);
						this._tagsid = value.id;
					}
					else
					{
						this._tagsid = default(long);
					}
					this.SendPropertyChanged("tag");
				}
			}
		}
		
		[Association(Name="article_tags_article", Storage="_article", ThisKey="articlesid", IsForeignKey=true)]
		public article article
		{
			get
			{
				return this._article.Entity;
			}
			set
			{
				article previousValue = this._article.Entity;
				if (((previousValue != value) 
							|| (this._article.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._article.Entity = null;
						previousValue.tags_articles.Remove(this);
					}
					this._article.Entity = value;
					if ((value != null))
					{
						value.tags_articles.Add(this);
						this._articlesid = value.id;
					}
					else
					{
						this._articlesid = default(long);
					}
					this.SendPropertyChanged("article");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.categories")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private System.Nullable<long> _parentid;
		
		private string _alias;
		
		private System.DateTime _date;
		
		private EntitySet<category> _categories;
		
		private EntitySet<articles_category> _articles_categories;
		
		private EntityRef<category> _category1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnparentidChanging(System.Nullable<long> value);
    partial void OnparentidChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public category()
		{
			this._categories = new EntitySet<category>(new Action<category>(this.attach_categories), new Action<category>(this.detach_categories));
			this._articles_categories = new EntitySet<articles_category>(new Action<articles_category>(this.attach_articles_categories), new Action<articles_category>(this.detach_articles_categories));
			this._category1 = default(EntityRef<category>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_parentid", DbType="BigInt")]
		public System.Nullable<long> parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				if ((this._parentid != value))
				{
					if (this._category1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnparentidChanging(value);
					this.SendPropertyChanging();
					this._parentid = value;
					this.SendPropertyChanged("parentid");
					this.OnparentidChanged();
				}
			}
		}
		
		[Column(Storage="_alias", DbType="VarChar(MAX)")]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Association(Name="category_category", Storage="_categories", OtherKey="parentid")]
		public EntitySet<category> categories
		{
			get
			{
				return this._categories;
			}
			set
			{
				this._categories.Assign(value);
			}
		}
		
		[Association(Name="category_articles_category", Storage="_articles_categories", OtherKey="categoriesid")]
		public EntitySet<articles_category> articles_categories
		{
			get
			{
				return this._articles_categories;
			}
			set
			{
				this._articles_categories.Assign(value);
			}
		}
		
		[Association(Name="category_category", Storage="_category1", ThisKey="parentid", IsForeignKey=true)]
		public category category1
		{
			get
			{
				return this._category1.Entity;
			}
			set
			{
				category previousValue = this._category1.Entity;
				if (((previousValue != value) 
							|| (this._category1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category1.Entity = null;
						previousValue.categories.Remove(this);
					}
					this._category1.Entity = value;
					if ((value != null))
					{
						value.categories.Add(this);
						this._parentid = value.id;
					}
					else
					{
						this._parentid = default(Nullable<long>);
					}
					this.SendPropertyChanged("category1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.category1 = this;
		}
		
		private void detach_categories(category entity)
		{
			this.SendPropertyChanging();
			entity.category1 = null;
		}
		
		private void attach_articles_categories(articles_category entity)
		{
			this.SendPropertyChanging();
			entity.category = this;
		}
		
		private void detach_articles_categories(articles_category entity)
		{
			this.SendPropertyChanging();
			entity.category = null;
		}
	}
	
	[Table(Name="dbo.authors")]
	public partial class author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _name;
		
		private string _lastname;
		
		private long _usersid;
		
		private string _description;
		
		private System.DateTime _date;
		
		private EntitySet<articles_author> _articles_authors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void OnusersidChanging(long value);
    partial void OnusersidChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public author()
		{
			this._articles_authors = new EntitySet<articles_author>(new Action<articles_author>(this.attach_articles_authors), new Action<articles_author>(this.detach_articles_authors));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[Column(Storage="_lastname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[Column(Storage="_usersid", DbType="BigInt NOT NULL")]
		public long usersid
		{
			get
			{
				return this._usersid;
			}
			set
			{
				if ((this._usersid != value))
				{
					this.OnusersidChanging(value);
					this.SendPropertyChanging();
					this._usersid = value;
					this.SendPropertyChanged("usersid");
					this.OnusersidChanged();
				}
			}
		}
		
		[Column(Storage="_description", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Association(Name="author_articles_author", Storage="_articles_authors", OtherKey="authorsid")]
		public EntitySet<articles_author> articles_authors
		{
			get
			{
				return this._articles_authors;
			}
			set
			{
				this._articles_authors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_articles_authors(articles_author entity)
		{
			this.SendPropertyChanging();
			entity.author = this;
		}
		
		private void detach_articles_authors(articles_author entity)
		{
			this.SendPropertyChanging();
			entity.author = null;
		}
	}
	
	[Table(Name="dbo.articles")]
	public partial class article : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _title;
		
		private string _alias;
		
		private string _introtext;
		
		private string _fulltext;
		
		private System.DateTime _date;
		
		private System.DateTime _date_published;
		
		private System.DateTime _date_pullback;
		
		private System.DateTime _date_lastmod;
		
		private long _hits;
		
		private int _modifications_count;
		
		private int _published;
		
		private long _level;
		
		private EntitySet<tags_article> _tags_articles;
		
		private EntitySet<articles_author> _articles_authors;
		
		private EntitySet<articles_category> _articles_categories;
		
		private EntitySet<comment> _comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OnintrotextChanging(string value);
    partial void OnintrotextChanged();
    partial void OnfulltextChanging(string value);
    partial void OnfulltextChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Ondate_publishedChanging(System.DateTime value);
    partial void Ondate_publishedChanged();
    partial void Ondate_pullbackChanging(System.DateTime value);
    partial void Ondate_pullbackChanged();
    partial void Ondate_lastmodChanging(System.DateTime value);
    partial void Ondate_lastmodChanged();
    partial void OnhitsChanging(long value);
    partial void OnhitsChanged();
    partial void Onmodifications_countChanging(int value);
    partial void Onmodifications_countChanged();
    partial void OnpublishedChanging(int value);
    partial void OnpublishedChanged();
    partial void OnlevelChanging(long value);
    partial void OnlevelChanged();
    #endregion
		
		public article()
		{
			this._tags_articles = new EntitySet<tags_article>(new Action<tags_article>(this.attach_tags_articles), new Action<tags_article>(this.detach_tags_articles));
			this._articles_authors = new EntitySet<articles_author>(new Action<articles_author>(this.attach_articles_authors), new Action<articles_author>(this.detach_articles_authors));
			this._articles_categories = new EntitySet<articles_category>(new Action<articles_category>(this.attach_articles_categories), new Action<articles_category>(this.detach_articles_categories));
			this._comments = new EntitySet<comment>(new Action<comment>(this.attach_comments), new Action<comment>(this.detach_comments));
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_alias", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[Column(Storage="_introtext", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string introtext
		{
			get
			{
				return this._introtext;
			}
			set
			{
				if ((this._introtext != value))
				{
					this.OnintrotextChanging(value);
					this.SendPropertyChanging();
					this._introtext = value;
					this.SendPropertyChanged("introtext");
					this.OnintrotextChanged();
				}
			}
		}
		
		[Column(Storage="_fulltext", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string fulltext
		{
			get
			{
				return this._fulltext;
			}
			set
			{
				if ((this._fulltext != value))
				{
					this.OnfulltextChanging(value);
					this.SendPropertyChanging();
					this._fulltext = value;
					this.SendPropertyChanged("fulltext");
					this.OnfulltextChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Column(Storage="_date_published", DbType="DateTime NOT NULL")]
		public System.DateTime date_published
		{
			get
			{
				return this._date_published;
			}
			set
			{
				if ((this._date_published != value))
				{
					this.Ondate_publishedChanging(value);
					this.SendPropertyChanging();
					this._date_published = value;
					this.SendPropertyChanged("date_published");
					this.Ondate_publishedChanged();
				}
			}
		}
		
		[Column(Storage="_date_pullback", DbType="DateTime NOT NULL")]
		public System.DateTime date_pullback
		{
			get
			{
				return this._date_pullback;
			}
			set
			{
				if ((this._date_pullback != value))
				{
					this.Ondate_pullbackChanging(value);
					this.SendPropertyChanging();
					this._date_pullback = value;
					this.SendPropertyChanged("date_pullback");
					this.Ondate_pullbackChanged();
				}
			}
		}
		
		[Column(Storage="_date_lastmod", DbType="DateTime NOT NULL")]
		public System.DateTime date_lastmod
		{
			get
			{
				return this._date_lastmod;
			}
			set
			{
				if ((this._date_lastmod != value))
				{
					this.Ondate_lastmodChanging(value);
					this.SendPropertyChanging();
					this._date_lastmod = value;
					this.SendPropertyChanged("date_lastmod");
					this.Ondate_lastmodChanged();
				}
			}
		}
		
		[Column(Storage="_hits", DbType="BigInt NOT NULL")]
		public long hits
		{
			get
			{
				return this._hits;
			}
			set
			{
				if ((this._hits != value))
				{
					this.OnhitsChanging(value);
					this.SendPropertyChanging();
					this._hits = value;
					this.SendPropertyChanged("hits");
					this.OnhitsChanged();
				}
			}
		}
		
		[Column(Storage="_modifications_count", DbType="Int NOT NULL")]
		public int modifications_count
		{
			get
			{
				return this._modifications_count;
			}
			set
			{
				if ((this._modifications_count != value))
				{
					this.Onmodifications_countChanging(value);
					this.SendPropertyChanging();
					this._modifications_count = value;
					this.SendPropertyChanged("modifications_count");
					this.Onmodifications_countChanged();
				}
			}
		}
		
		[Column(Storage="_published", DbType="Int NOT NULL")]
		public int published
		{
			get
			{
				return this._published;
			}
			set
			{
				if ((this._published != value))
				{
					this.OnpublishedChanging(value);
					this.SendPropertyChanging();
					this._published = value;
					this.SendPropertyChanged("published");
					this.OnpublishedChanged();
				}
			}
		}
		
		[Column(Name="[level]", Storage="_level", DbType="BigInt NOT NULL")]
		public long level
		{
			get
			{
				return this._level;
			}
			set
			{
				if ((this._level != value))
				{
					this.OnlevelChanging(value);
					this.SendPropertyChanging();
					this._level = value;
					this.SendPropertyChanged("level");
					this.OnlevelChanged();
				}
			}
		}
		
		[Association(Name="article_tags_article", Storage="_tags_articles", OtherKey="articlesid")]
		public EntitySet<tags_article> tags_articles
		{
			get
			{
				return this._tags_articles;
			}
			set
			{
				this._tags_articles.Assign(value);
			}
		}
		
		[Association(Name="article_articles_author", Storage="_articles_authors", OtherKey="articlesid")]
		public EntitySet<articles_author> articles_authors
		{
			get
			{
				return this._articles_authors;
			}
			set
			{
				this._articles_authors.Assign(value);
			}
		}
		
		[Association(Name="article_articles_category", Storage="_articles_categories", OtherKey="articlesid")]
		public EntitySet<articles_category> articles_categories
		{
			get
			{
				return this._articles_categories;
			}
			set
			{
				this._articles_categories.Assign(value);
			}
		}
		
		[Association(Name="article_comment", Storage="_comments", OtherKey="articlesid")]
		public EntitySet<comment> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tags_articles(tags_article entity)
		{
			this.SendPropertyChanging();
			entity.article = this;
		}
		
		private void detach_tags_articles(tags_article entity)
		{
			this.SendPropertyChanging();
			entity.article = null;
		}
		
		private void attach_articles_authors(articles_author entity)
		{
			this.SendPropertyChanging();
			entity.article = this;
		}
		
		private void detach_articles_authors(articles_author entity)
		{
			this.SendPropertyChanging();
			entity.article = null;
		}
		
		private void attach_articles_categories(articles_category entity)
		{
			this.SendPropertyChanging();
			entity.article = this;
		}
		
		private void detach_articles_categories(articles_category entity)
		{
			this.SendPropertyChanging();
			entity.article = null;
		}
		
		private void attach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.article = this;
		}
		
		private void detach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.article = null;
		}
	}
	
	[Table(Name="dbo.articles_authors")]
	public partial class articles_author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _articlesid;
		
		private long _authorsid;
		
		private System.DateTime _date;
		
		private EntityRef<article> _article;
		
		private EntityRef<author> _author;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnarticlesidChanging(long value);
    partial void OnarticlesidChanged();
    partial void OnauthorsidChanging(long value);
    partial void OnauthorsidChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public articles_author()
		{
			this._article = default(EntityRef<article>);
			this._author = default(EntityRef<author>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_articlesid", DbType="BigInt NOT NULL")]
		public long articlesid
		{
			get
			{
				return this._articlesid;
			}
			set
			{
				if ((this._articlesid != value))
				{
					if (this._article.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnarticlesidChanging(value);
					this.SendPropertyChanging();
					this._articlesid = value;
					this.SendPropertyChanged("articlesid");
					this.OnarticlesidChanged();
				}
			}
		}
		
		[Column(Storage="_authorsid", DbType="BigInt NOT NULL")]
		public long authorsid
		{
			get
			{
				return this._authorsid;
			}
			set
			{
				if ((this._authorsid != value))
				{
					if (this._author.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnauthorsidChanging(value);
					this.SendPropertyChanging();
					this._authorsid = value;
					this.SendPropertyChanged("authorsid");
					this.OnauthorsidChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Association(Name="article_articles_author", Storage="_article", ThisKey="articlesid", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public article article
		{
			get
			{
				return this._article.Entity;
			}
			set
			{
				article previousValue = this._article.Entity;
				if (((previousValue != value) 
							|| (this._article.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._article.Entity = null;
						previousValue.articles_authors.Remove(this);
					}
					this._article.Entity = value;
					if ((value != null))
					{
						value.articles_authors.Add(this);
						this._articlesid = value.id;
					}
					else
					{
						this._articlesid = default(long);
					}
					this.SendPropertyChanged("article");
				}
			}
		}
		
		[Association(Name="author_articles_author", Storage="_author", ThisKey="authorsid", IsForeignKey=true)]
		public author author
		{
			get
			{
				return this._author.Entity;
			}
			set
			{
				author previousValue = this._author.Entity;
				if (((previousValue != value) 
							|| (this._author.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._author.Entity = null;
						previousValue.articles_authors.Remove(this);
					}
					this._author.Entity = value;
					if ((value != null))
					{
						value.articles_authors.Add(this);
						this._authorsid = value.id;
					}
					else
					{
						this._authorsid = default(long);
					}
					this.SendPropertyChanged("author");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.articles_categories")]
	public partial class articles_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _articlesid;
		
		private long _categoriesid;
		
		private System.DateTime _date;
		
		private EntityRef<article> _article;
		
		private EntityRef<category> _category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnarticlesidChanging(long value);
    partial void OnarticlesidChanged();
    partial void OncategoriesidChanging(long value);
    partial void OncategoriesidChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
		
		public articles_category()
		{
			this._article = default(EntityRef<article>);
			this._category = default(EntityRef<category>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_articlesid", DbType="BigInt NOT NULL")]
		public long articlesid
		{
			get
			{
				return this._articlesid;
			}
			set
			{
				if ((this._articlesid != value))
				{
					if (this._article.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnarticlesidChanging(value);
					this.SendPropertyChanging();
					this._articlesid = value;
					this.SendPropertyChanged("articlesid");
					this.OnarticlesidChanged();
				}
			}
		}
		
		[Column(Storage="_categoriesid", DbType="BigInt NOT NULL")]
		public long categoriesid
		{
			get
			{
				return this._categoriesid;
			}
			set
			{
				if ((this._categoriesid != value))
				{
					if (this._category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncategoriesidChanging(value);
					this.SendPropertyChanging();
					this._categoriesid = value;
					this.SendPropertyChanged("categoriesid");
					this.OncategoriesidChanged();
				}
			}
		}
		
		[Column(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[Association(Name="article_articles_category", Storage="_article", ThisKey="articlesid", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public article article
		{
			get
			{
				return this._article.Entity;
			}
			set
			{
				article previousValue = this._article.Entity;
				if (((previousValue != value) 
							|| (this._article.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._article.Entity = null;
						previousValue.articles_categories.Remove(this);
					}
					this._article.Entity = value;
					if ((value != null))
					{
						value.articles_categories.Add(this);
						this._articlesid = value.id;
					}
					else
					{
						this._articlesid = default(long);
					}
					this.SendPropertyChanged("article");
				}
			}
		}
		
		[Association(Name="category_articles_category", Storage="_category", ThisKey="categoriesid", IsForeignKey=true)]
		public category category
		{
			get
			{
				return this._category.Entity;
			}
			set
			{
				category previousValue = this._category.Entity;
				if (((previousValue != value) 
							|| (this._category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._category.Entity = null;
						previousValue.articles_categories.Remove(this);
					}
					this._category.Entity = value;
					if ((value != null))
					{
						value.articles_categories.Add(this);
						this._categoriesid = value.id;
					}
					else
					{
						this._categoriesid = default(long);
					}
					this.SendPropertyChanged("category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.comments")]
	public partial class comment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _title;
		
		private string _text;
		
		private System.Nullable<long> _usersid;
		
		private string _useralias;
		
		private System.Nullable<long> _parentid;
		
		private string _email;
		
		private string _ip;
		
		private long _articlesid;
		
		private EntitySet<comment> _comments;
		
		private EntityRef<article> _article;
		
		private EntityRef<comment> _comment1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OnusersidChanging(System.Nullable<long> value);
    partial void OnusersidChanged();
    partial void OnuseraliasChanging(string value);
    partial void OnuseraliasChanged();
    partial void OnparentidChanging(System.Nullable<long> value);
    partial void OnparentidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnipChanging(string value);
    partial void OnipChanged();
    partial void OnarticlesidChanging(long value);
    partial void OnarticlesidChanged();
    #endregion
		
		public comment()
		{
			this._comments = new EntitySet<comment>(new Action<comment>(this.attach_comments), new Action<comment>(this.detach_comments));
			this._article = default(EntityRef<article>);
			this._comment1 = default(EntityRef<comment>);
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_title", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[Column(Storage="_text", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[Column(Storage="_usersid", DbType="BigInt")]
		public System.Nullable<long> usersid
		{
			get
			{
				return this._usersid;
			}
			set
			{
				if ((this._usersid != value))
				{
					this.OnusersidChanging(value);
					this.SendPropertyChanging();
					this._usersid = value;
					this.SendPropertyChanged("usersid");
					this.OnusersidChanged();
				}
			}
		}
		
		[Column(Storage="_useralias", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string useralias
		{
			get
			{
				return this._useralias;
			}
			set
			{
				if ((this._useralias != value))
				{
					this.OnuseraliasChanging(value);
					this.SendPropertyChanging();
					this._useralias = value;
					this.SendPropertyChanged("useralias");
					this.OnuseraliasChanged();
				}
			}
		}
		
		[Column(Storage="_parentid", DbType="BigInt")]
		public System.Nullable<long> parentid
		{
			get
			{
				return this._parentid;
			}
			set
			{
				if ((this._parentid != value))
				{
					if (this._comment1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnparentidChanging(value);
					this.SendPropertyChanging();
					this._parentid = value;
					this.SendPropertyChanged("parentid");
					this.OnparentidChanged();
				}
			}
		}
		
		[Column(Storage="_email", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[Column(Storage="_ip", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ip
		{
			get
			{
				return this._ip;
			}
			set
			{
				if ((this._ip != value))
				{
					this.OnipChanging(value);
					this.SendPropertyChanging();
					this._ip = value;
					this.SendPropertyChanged("ip");
					this.OnipChanged();
				}
			}
		}
		
		[Column(Storage="_articlesid", DbType="BigInt NOT NULL")]
		public long articlesid
		{
			get
			{
				return this._articlesid;
			}
			set
			{
				if ((this._articlesid != value))
				{
					if (this._article.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnarticlesidChanging(value);
					this.SendPropertyChanging();
					this._articlesid = value;
					this.SendPropertyChanged("articlesid");
					this.OnarticlesidChanged();
				}
			}
		}
		
		[Association(Name="comment_comment", Storage="_comments", OtherKey="parentid")]
		public EntitySet<comment> comments
		{
			get
			{
				return this._comments;
			}
			set
			{
				this._comments.Assign(value);
			}
		}
		
		[Association(Name="article_comment", Storage="_article", ThisKey="articlesid", IsForeignKey=true)]
		public article article
		{
			get
			{
				return this._article.Entity;
			}
			set
			{
				article previousValue = this._article.Entity;
				if (((previousValue != value) 
							|| (this._article.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._article.Entity = null;
						previousValue.comments.Remove(this);
					}
					this._article.Entity = value;
					if ((value != null))
					{
						value.comments.Add(this);
						this._articlesid = value.id;
					}
					else
					{
						this._articlesid = default(long);
					}
					this.SendPropertyChanged("article");
				}
			}
		}
		
		[Association(Name="comment_comment", Storage="_comment1", ThisKey="parentid", IsForeignKey=true)]
		public comment comment1
		{
			get
			{
				return this._comment1.Entity;
			}
			set
			{
				comment previousValue = this._comment1.Entity;
				if (((previousValue != value) 
							|| (this._comment1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._comment1.Entity = null;
						previousValue.comments.Remove(this);
					}
					this._comment1.Entity = value;
					if ((value != null))
					{
						value.comments.Add(this);
						this._parentid = value.id;
					}
					else
					{
						this._parentid = default(Nullable<long>);
					}
					this.SendPropertyChanged("comment1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.comment1 = this;
		}
		
		private void detach_comments(comment entity)
		{
			this.SendPropertyChanging();
			entity.comment1 = null;
		}
	}
}
#pragma warning restore 1591
