<?xml version="1.0" encoding="utf-8"?>
<Database Name="CMS" Class="ArticleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\CMS.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tags" Member="tags">
    <Type Name="tag">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="tag_tags_article" Member="tags_articles" OtherKey="tagsid" Type="tags_article" />
    </Type>
  </Table>
  <Table Name="dbo.tags_articles" Member="tags_articles">
    <Type Name="tags_article">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tagsid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="articlesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="tag_tags_article" Member="tag" ThisKey="tagsid" Type="tag" IsForeignKey="true" />
      <Association Name="article_tags_article" Member="article" ThisKey="articlesid" Type="article" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.categories" Member="categories">
    <Type Name="category">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="parentid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="alias" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="category_category" Member="categories" OtherKey="parentid" Type="category" />
      <Association Name="category_articles_category" Member="articles_categories" OtherKey="categoriesid" Type="articles_category" />
      <Association Name="category_category" Member="category1" ThisKey="parentid" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.authors" Member="authors">
    <Type Name="author">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usersid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="author_articles_author" Member="articles_authors" OtherKey="authorsid" Type="articles_author" />
    </Type>
  </Table>
  <Table Name="dbo.articles" Member="articles">
    <Type Name="article">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="alias" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="introtext" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="fulltext" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="date_published" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="date_pullback" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="date_lastmod" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="hits" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="modifications_count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="published" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="article_tags_article" Member="tags_articles" OtherKey="articlesid" Type="tags_article" />
      <Association Name="article_articles_author" Member="articles_authors" OtherKey="articlesid" Type="articles_author" />
      <Association Name="article_articles_category" Member="articles_categories" OtherKey="articlesid" Type="articles_category" />
      <Association Name="article_comment" Member="comments" OtherKey="articlesid" Type="comment" />
    </Type>
  </Table>
  <Table Name="dbo.articles_authors" Member="articles_authors">
    <Type Name="articles_author">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="articlesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="authorsid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="article_articles_author" Member="article" ThisKey="articlesid" Type="article" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="author_articles_author" Member="author" ThisKey="authorsid" Type="author" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.articles_categories" Member="articles_categories">
    <Type Name="articles_category">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="articlesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="categoriesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="article_articles_category" Member="article" ThisKey="articlesid" Type="article" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="category_articles_category" Member="category" ThisKey="categoriesid" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.comments" Member="comments">
    <Type Name="comment">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="usersid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="useralias" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="parentid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ip" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="articlesid" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="comment_comment" Member="comments" OtherKey="parentid" Type="comment" />
      <Association Name="article_comment" Member="article" ThisKey="articlesid" Type="article" IsForeignKey="true" />
      <Association Name="comment_comment" Member="comment1" ThisKey="parentid" Type="comment" IsForeignKey="true" />
    </Type>
  </Table>
</Database>